easy = [
    'star',
    'lunar',
    'moon',
    'earth',
    'space',
    'god',
    'void',
    'comet',
    'holy',
    'sky',
    'sun',
    'stars',
    'mars',
    'aries',
    'lupus',
    'libra',
    'leo',
    'orion',
    'virgo',
    'crater',
    'nasa',
    'divine',
    'cosmic',
    'cosmos',
    'planet',
    'aurora',
    'angels',
    'astral',
    'ancient',
    'meteor',
    'zodiac',
    'galaxy',
    'uranus',
    'cancer',
    'gemini',
    'taurus',
    'venus',
    'pluto',
    'sirius',
    'saturn',
    'nebula'
]

medium = [
    'heavenly',
    'ethereal',
    'galactic',
    'gravity',
    'mystical',
    'planetary',
    'radiation',
    'angelic',
    'solstice',
    'starlight',
    'heavens',
    'universe',
    'spiritual',
    'asteroids',
    'eternal',
    'jupitar',
    'horoscope',
    'wormhole',
    'stellar',
    'andromeda',
    'supernova',
    'astrology',
    'orbiting',
    'mercury',
    'jupitar',
    'neptune',
    'adromeda',
    'aquarius',
    'capricorn',
    'cassiopeia',
    'centaurus',
    'pegasus',
    'scorpius',
    'astronaut',
    'cosmology',
    'meteoroid',
    'satellite',
    'starlight',
    'sputnik',
    'solstice'
]

hard = [
    'interstellar',
    'mythological',
    'extraterrestrial',
    'celestiral sphere',
    'sagittarius',
    'terrestrial',
    'celestial mechanics',
    'solar eclipse',
    'astronomical',
    'hubble telescope',
    'astronomers',
    'constellation',
    'ursa major',
    'north star',
    'big bang theory',
    'crescent moon',
    'black hole',
    'dwarf planet',
    'falling star',
    'meteor shower',
    'the milky way',
    'new moon',
    'shooting star',
    'solar system',
    'spectroscope',
    'space station',
    'solar eclipse',
    'weightlessness'
]
